version: 4.0.0.{build}

os: Visual Studio 2017

branches:
  except:
    - configdata
    - gh-pages

environment:
  matrix:
  - IdeVersion: VS2017
  SKIP_PAUSE: TRUE
  ARCHIVE_WITH_PDB: TRUE

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# Build settings, not to be confused with "before_build" and "after_build".
# "project" is relative to the original build directory and not influenced by directory changes in "before_build".
build:
  # enable MSBuild parallel builds
  parallel: true
  # MSBuild verbosity level
  verbosity: minimal

cache:
  #- packages -> **\packages.config      # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - packages\WiX.3.11.0 -> Setup\packages.config

install:
- cmd: git submodule update --init --recursive
- cmd: echo /logger:"%ProgramFiles%\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll">> Directory.Build.rsp


# to run your custom scripts instead of automatic MSBuild
build_script:
- ps: |
    Write-Output "Platform: $env:IdeVersion"

    # for release branches mark the repo as clean
    if (!$env:APPVEYOR_PULL_REQUEST_TITLE -and $env:APPVEYOR_REPO_BRANCH.StartsWith("release/")) {
      & .\Build\Mark-RepoClean.ps1
    }

    # build
    & .\Build\Build.ps1 -restore -build -Configuration Release -bl -version $env:APPVEYOR_BUILD_VERSION
      if ($LastExitCode -ne 0) { exit $LastExitCode; }

    # for pull-reqests enforce updated translations
    # if any strings have changed and the author hasn't updated translations,
    # we will get changes to either English.xlf and/or English.Plugins.xlf - if so, fail the build
    if ($env:APPVEYOR_PULL_REQUEST_TITLE) {
      & .\Build\Build.ps1 -loc -Configuration Release
      if ($LastExitCode -ne 0) { exit $LastExitCode; }

      # stage all modified files, as some translations yield no content change, but are seeing as file changed until stages
      git add *.xlf --ignore-errors

      # look for any modified xlf files, and if any - fail the build
      Write-Host "[LOG] ...checking if XLF files changed" -ForegroundColor Green
      $output = $(git status --porcelain)| ?{ $_.EndsWith('.xlf') }
      if ($output) {
        & git diff --cached > git-diff-xlf.txt
        Push-AppveyorArtifact git-diff-xlf.txt

        throw "Please update English translations and re-submit the pull-request.`r`nFor more information please refer to https://github.com/gitextensions/gitextensions/wiki/Translations";
      }
    }


# to run your custom scripts instead of automatic tests
test_script:
- ps: |
    & .\Build\Build.ps1 -test -Configuration Release


# scripts to run after tests
after_test:
- ps: |
    & .\Build\Build.ps1 -pack -Configuration Release -bl -version $env:APPVEYOR_BUILD_VERSION


artifacts:
  # upload the generated portable archive only
  - path: 'Setup/GitExtensions-Portable-*.zip'
  - path: 'Setup/GitExtensions-pdbs-*.zip'
  - path: 'GitExtensionsVSIX/bin/Release/GitExtensionsVSIX.vsix'
