name: Basic validation
run-name: Validation of pull-request \#${{ github.event.number }} by @${{ github.actor }}

on: 
  pull_request:
    paths-ignore:
    - .github/*
    - docs/*
    - eng/Version.Details.xml
    - CODE-OF-CONDUCT.md
    - LICENSE.TXT
    - PATENTS.TXT
    - README.md
    - SECURITY.md
    - THIRD-PARTY-NOTICES.TXT

jobs:
  build:
    runs-on: windows-latest
    env:
      BUILD_CONFIG: Release
    steps:
    #- uses: actions/checkout@v2.0.0
    - name: Set variables
      run: |
          echo "ARTIFACTS_PATH=${{ github.workspace }}/artifacts/" >> $GITHUB_ENV
          echo "LOGS_PATH=$env:ARTIFACTS_PATH/log/${{ env.BUILD_CONFIG }}/" >> $GITHUB_ENV
          echo "BUILD_SCRIPT=${{ github.workspace }}/eng/cibuild.cmd" >> $GITHUB_ENV
    - name: Print a greeting
      run: |
          echo ${{ env.ARTIFACTS_PATH }} // ${{ env.LOGS_PATH }} // ${{ env.BUILD_SCRIPT }}
          echo $ARTIFACTS_PATH // $LOGS_PATH // $BUILD_SCRIPT
          echo $env:ARTIFACTS_PATH // $env:LOGS_PATH // $env:BUILD_SCRIPT
